baseURL = "https://revoltzero.github.io"
languageCode = "en-us"
title = "Revolt Zero"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/"

# meta data
author = "Themefisher"
description = "This is meta description"


[Languages.en]
weight = 2
languageCode = "en-us"
title = "Revolt Zero"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo2.png"
menufixed = false

footerDescription = "The Revolt Zero is a team of highly talented individuals with diverse backgrounds and skills in the field of cybersecurity."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable = true
heading = "Securing Tomorrow's Digital Landscape Today"
description = "we are committed to making the internet a safer place for everyone. Our focus on developing our skills and knowledge is driven by a shared vision of improving cybersecurity practices and protocols. We believe that by working together, we can achieve our goals and help create a safer and more secure digital landscape for all."
button = true
btnText = "Know More"
btnURL = "https://github.com/revoltzero"
videoThumb = "images/slider/cover.png"
videoURL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

# About 2 Section
[Languages.en.params.aboutSm]
enable = true
title = "We have explored the digital landscape with passion for cyber security"
description = "As a team, we are passionate about cybersecurity and take pride in our ability to tackle complex challenges with ease. Our expertise in security research and community services allows us to make meaningful contributions to the industry and society at large."

# Blog Section On Homepage
[Languages.en.params.blog]
enable = true
title = "Blog."
subtitle = "We also publish Blog about any interesting research, security incident & CTF challenge writeup."

# Contact Section
[Languages.en.params.contact]
enable = true
title = "Contact Us."
subtitle = "For any inquiries, please contact us at: teamrevoltzero@gmail.com"


# Call to Action Section on About Page
[Languages.en.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's Create Something Together"
subtitle = "Feel free to reach out for discussions, collaboration, or just to say hi. Together, we can make the tech world more secure and fascinating!"
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "about"
url = "about/"
weight = 1
[[menu.nav]]
name = "service"
url = "service/"
weight = 2
[[menu.nav]]
name = "blog"
url = "blog/"
weight = 3
[[menu.nav]]
name = "contact"
url = "contact/"
weight = 4

# Footer Service Menu
[[menu.service]]
name = "graphicdesign"
url = "service/"
weight = 1
[[menu.service]]
name = "webdesign"
url = "service/"
weight = 2
[[menu.service]]
name = "webdevelopment"
url = "service/"
weight = 3

# Footer Quick links Menu
[[menu.quicklink]]
name = "partners"
url = "https://github.com/revoltzero"
weight = 1
[[menu.quicklink]]
name = "badges11"
url = "https://twitter.com/teamrevoltzero"
weight = 2
[[menu.quicklink]]
name = "faqs"
url = "https://www.linkedin.com/company/theresurrectedodyssey/"
weight = 3
[[menu.quicklink]]
name = "badges"
url = "https://www.facebook.com/teamrevoltzero"
weight = 4
